#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

pgrep -x xfsettingsd >/dev/null || xfsettingsd &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 35

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

systemd restart systemd-resolved.service
setxkbmap cz
polybar &
picom &
